# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Lulu_UsersList' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Lulu_UsersList
  pod 'Alamofire'

  target 'Lulu_UsersListTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Lulu_UsersListUITests' do
    # Pods for testing
  end

end
